# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Doctor.create(name: 'Neo', jabatan: 'Doktor Gigi')
Doctor.create(name: 'Brooklyn', jabatan: 'Doktor Gigi')
Doctor.create(name: 'Kerys', jabatan: 'Doktor Gigi')
Doctor.create(name: 'Kie', jabatan: 'Doktor Gigi')
Doctor.create(name: 'Blossom', jabatan: 'Doktor Gigi')
Doctor.create(name: 'Lucie', jabatan: 'Doktor Gigi')
Doctor.create(name: 'Milla', jabatan: 'Doktor Gigi')
Doctor.create(name: 'Antoni', jabatan: 'Doktor Gigi')
Doctor.create(name: 'Tamera', jabatan: 'Doktor Gigi')
Doctor.create(name: 'Hilary', jabatan: 'Doktor Gigi')
Doctor.create(name: 'nico', jabatan: 'Doktor Gigi')
Hospital.create(hospital_name:'Tranquil Valley Hospital', address: 'jakarta')
Hospital.create(hospital_name:'Sapphire Lake Hospital', address: 'jakarta')
Hospital.create(hospital_name:'Sacred Heart Clinic', address: 'jakarta')
Hospital.create(hospital_name:'Grandview Community Hospital', address: 'jakarta')
Hospital.create(hospital_name:'Broadwater Community Hospital', address: 'jakarta')
Hospital.create(hospital_name:'Lowland Hospital', address: 'jakarta')
Hospital.create(hospital_name:'Grand Garden Medical Clinic', address: 'jakarta')
Hospital.create(hospital_name:'Summit Clinic', address: 'jakarta')
Hospital.create(hospital_name:'Highlands Clinic', address: 'jakarta')
Hospital.create(hospital_name:'United Clinic', address: 'jakarta')
DoctorSchedule.create(id_doctor: 1, id_hospital: 1, schedule_day: 'Monday', start_time: '2020-09-21 20:45:17', end_time: '2020-09-21 23:45:17')
DoctorSchedule.create(id_doctor: 2, id_hospital: 3, schedule_day: 'Monday', start_time: '2020-09-21 20:45:17', end_time: '2020-09-21 23:45:17')
DoctorSchedule.create(id_doctor: 4, id_hospital: 2, schedule_day: 'Sunday', start_time: '2020-09-20 20:45:17', end_time: '2020-09-21 22:45:17')
