# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Doctor.create(name: 'nico', jabatan: 'Doktor Gigi')
Doctor.create(name: 'nic', jabatan: 'Doktor Gigi')
Doctor.create(name: 'nicom', jabatan: 'Doktor Gigi')
Doctor.create(name: 'nicob', jabatan: 'Doktor Gigi')
Doctor.create(name: 'nicof', jabatan: 'Doktor Gigi')
Doctor.create(name: 'nicoff', jabatan: 'Doktor Gigi')
Doctor.create(name: 'nicob', jabatan: 'Doktor Gigi')
Doctor.create(name: 'nicos', jabatan: 'Doktor Gigi')
Doctor.create(name: 'nicoe', jabatan: 'Doktor Gigi')
Doctor.create(name: 'nicode', jabatan: 'Doktor Gigi')
Doctor.create(name: 'nicodd', jabatan: 'Doktor Gigi')
Doctor.create(name: 'nicon', jabatan: 'Doktor Gigi')
Doctor.create(name: 'niconh', jabatan: 'Doktor Gigi')
Doctor.create(name: 'niconhh', jabatan: 'Doktor Gigi')
Doctor.create(name: 'nicogg', jabatan: 'Doktor Gigi')
Doctor.create(name: 'nicogf', jabatan: 'Doktor Gigi')
Hospital.create(hospital_name:'Tranquil Valley Hospital', address: 'jakarta')
Hospital.create(hospital_name:'Sapphire Lake Hospital', address: 'jakarta')
Hospital.create(hospital_name:'Sacred Heart Clinic', address: 'jakarta')
Hospital.create(hospital_name:'Grandview Community Hospital', address: 'jakarta')
Hospital.create(hospital_name:'Broadwater Community Hospital', address: 'jakarta')
Hospital.create(hospital_name:'Lowland Hospital', address: 'jakarta')
Hospital.create(hospital_name:'Grand Garden Medical Clinic', address: 'jakarta')
Hospital.create(hospital_name:'Summit Clinic', address: 'jakarta')
Hospital.create(hospital_name:'Highlands Clinic', address: 'jakarta')
Hospital.create(hospital_name:'United Clinic', address: 'jakarta')
